ControleDeProjetos/Models/Acao.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ControleDeProjetos.Models
{
    public class Acao
    {
        public int Id { get; set; }
        public int ProjetoId { get; set; }
        public string Descricao { get; set; }
        public bool Concluido { get; set; }
    }
}

ControleDeProjetos/Models/DbContexto.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ControleDeProjetos.Models
{
    public class DbContexto : DbContext
    {
        public DbSet<Acao> Acao { get; set; }
        public DbSet<Projeto> Projeto { get; set; }

        public DbContexto(DbContextOptions<DbContexto> opcoes) : base(opcoes)
        {

        }
    }
}

ControleDeProjetos/Models/Projeto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ControleDeProjetos.Models
{
    public class Projeto
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Observacao { get; set; }

        public ICollection<Acao> Acoes { get; set; }
    }
}

ControleDeProjetos/Controllers/ProjetoController.cs
using ControleDeProjetos.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ControleDeProjetos.Controllers
{
    public class ProjetoController : Controller
    {
        DbContexto _contexto;

        public ProjetoController(DbContexto contexto)
        {
            _contexto = contexto;
        }

        public IActionResult Index()
        {
            return View(_contexto.Projeto.ToList());
        }

        [HttpGet]
        public IActionResult Editar(int id)
        {
            var projeto = _contexto.Projeto.FirstOrDefault(p => p.Id == id);
            if (projeto == null)
            {
                return NotFound();
            }

            return View(projeto);
        }

        [HttpPost]
        public IActionResult Editar(Projeto projeto)
        {
            try
            {
                var projetoEditar = _contexto.Projeto.FirstOrDefault(p => p.Id == projeto.Id);

                if (projetoEditar == null)
                {
                    return NotFound();
                }

                projetoEditar.Titulo = projeto.Titulo;
                projetoEditar.Observacao = projeto.Observacao;

                _contexto.SaveChanges();

                TempData["mensagem"] = $"{projetoEditar.Titulo} foi salvo!";

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["mensagem"] = ex.Message;
                return BadRequest();
            }
        }

        public IActionResult Detalhes(int id)
        {
            return View();
        }

        public IActionResult Novo()
        {
            return View(new Projeto());
        }

        [HttpPost]
        public IActionResult Novo(Projeto projeto)
        {
            try
            {
                           
                if (ModelState.IsValid)
                {
                    _contexto.Projeto.Add(projeto);
                    _contexto.SaveChanges();
                    TempData["mensagem"] = $"{projeto.Titulo} salvo com sucesso!";
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(projeto);
                }
            }
            catch (Exception ex)
            {
                TempData["mensagem"] = ex.Message;
                return BadRequest();
            }
        }
    }
}

ControleDeProjetos/Views/Projeto/Editar.cshtml
@model ControleDeProjetos.Models.Projeto

<h2>Editar</h2>
<form asp-action="Editar" method="post">
    <h4>Projeto</h4>
    <input type="hidden" asp-for="Id"/>
    <div class="form-group">
        <label asp-for="Titulo" class="col-md-2 form-control-label"></label>
        <div class="col-md-10">
            <input asp-for="Titulo" class="form-control"/>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Observacao" class="col-md-2 form-control-label"></label>
        <div class="col-md-10">
            <input asp-for="Observacao" class="form-control" />
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            <input type="submit" value="Salvar" class="btn"/>
        </div>
    </div>
</form>

ControleDeProjetos/Views/Projeto/Index.cshtml
@model List<ControleDeProjetos.Models.Projeto>

@if (TempData["mensagem"] != null)
{
    <div class="alert">@TempData["mensagem"]</div>
}
<table class="table">
    <thead>
        <tr>
            <th>
                Título
            </th>
            <th>
                Observação
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelitem => item.Titulo)
                </td>
                <td>
                    @Html.DisplayFor(modelitem => item.Observacao)
                </td>
                <td>
                    <a asp-action="Editar" asp-route-Id="@item.Id">Editar</a> |
                    <a asp-action="Detalhes" asp-route-id="@item.Id">Detalhes</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }

    </tbody>
</table>

<div class="text-center">
    <a asp-action="Novo" class="btn btn-primary">Novo Projeto</a>
</div>

ControleDeProjetos/Views/Projeto/Novo.cshtml
@model ControleDeProjetos.Models.Projeto

<h2>Novo</h2>
<form asp-action="Novo" method="post">
    <h4>Projeto</h4>
    <input type="hidden" asp-for="Id"/>
    <div class="form-group">
        <label asp-for="Titulo" class="col-md-2 form-control-label"></label>
        <div class="col-md-10">
            <input asp-for="Titulo" class="form-control"/>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Observacao" class="col-md-2 form-control-label"></label>
        <div class="col-md-10">
            <input asp-for="Observacao" class="form-control" />
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            <input type="submit" value="Salvar" class="btn"/>
        </div>
    </div>
</form>

ControleDeProjetos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Controle de Projetos</title>

    
        <link rel="stylesheet" asp-href-include="/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar navbar-inverse" role="navigation">
                <a class="navbar-brand" href="#">Controle de Projetos</a>
            </div>
            <div class="row panel">
                <div id="categorias" class="col-xs-3">
                    <ul>
                        <li><a asp-area="" asp-controller="Projeto" asp-action="Index">Projetos</a></li>
                        <li><a asp-area="" asp-controller="Acao" asp-action="Index">Ações</a></li>
                    </ul>
                </div>
                <div class="col-xs-8">
                    @RenderBody()
                </div>
            </div>
        </div>
    </nav>
        <hr />
        <footer>
            <p>&copy; 2017 - Controle de Projetos</p>
        </footer>

    @RenderSection("Scripts", required: false)
</body>
</html>